[colors]
ansi = [ "{color0}", "{color1}", "{color2}", "{color3}", "{color4}", "{color5}", "{color6}", "{color7}" ]
brights = [ "{color8}", "{color9}", "{color10}", "{color11}", "{color12}", "{color8}", "{color4}", "{color6}" ]

background = "{color0}"
foreground = "{color6}"

compose_cursor = '#ffffff'
cursor_bg = "#ffffff"
cursor_border = "{color6}"
cursor_fg = "{color9}"

selection_bg = "{color2}"
selection_fg = "{color6}"

scrollbar_thumb = '{color1}'
split = '{color1}'

[colors.indexed]

[colors.tab_bar]
background = "{color0}"

[colors.tab_bar.active_tab]
bg_color = "{color11}"
fg_color = "{color0}"
intensity = "Normal"
underline = "None"
italic = false
strikethrough = false

[colors.tab_bar.inactive_tab]
bg_color = "{color0}"
fg_color = "{color11}"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab_hover]
bg_color = "{color1}"
fg_color = "{color5}"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab]
bg_color = "{color0}"
fg_color = "{color11}"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab_hover]
bg_color = "{color2}"
fg_color = "{color6}"
intensity = "Normal"
italic = true
strikethrough = false
underline = "None"

[metadata]
name = 'hardhacker'
origin_url = 'https://github.com/hardhackerlabs/theme-wezterm'
